### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by aahmed-se** [vlang/vid#16]
```
v .
.vid.c:118:10: fatal error: 'ft2build.h' file not found
#include "ft2build.h"
         ^~~~~~~~~~~~
1 error generated.V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```

brew install freetype is done how do I pass header locations to v during compilation.

```
 v version
V 0.1.17
```

```
osx version
10.14.6
```

**Comment by biancode** [comment]
v .
In file included from .vid.c:114:0:
/home/vlang/v/thirdparty/glfw/GLFW/glfw3.h:202:12: fatal error: GL/gl.h: Datei oder Verzeichnis nicht gefunden
   #include <GL/gl.h>
            ^~~~~~~~~
compilation terminated.
V panic: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

Peppermint 9
v 0.1.17

If I solve this with the mesa-common-dev it gets the same error as reported here.

**Comment by biancode** [comment]
that worked for me:

`sudo apt install libglfw3 libglfw3-dev libfreetype6-dev libcurl3-dev`

**Comment by medvednikov** [comment]
This was fixed, readme was updated.

**Comment by tbmale** [comment]
```
D:\_dev\vid\vid.tmp.c:140:10: fatal error: ft2build.h: No such file or directory
  140 | #include "ft2build.h"
      |          ^~~~~~~~~~~~
compilation terminated.
V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
```
cloned master and buit v today
using msys2 & mingw64
added glfw & freetype with
```
pacman -S mingw-w64-x86_64-glfw
pacman -S mingw-w64-x86_64-freetype
```
