### ISSUE TITLE
When will it be released ?

### ISSUE THREAD

**Issue by noelzubin** [vlang/vid#2]
When will the code be released? 

cant wait to try it out.

**Comment by anthony-y** [comment]
For real, I thought it would drop with the V compiler but apparently not 😭

**Comment by RustemB** [comment]
V 0.2.0

**Comment by medvednikov** [comment]
July 7.

**Comment by anthony-y** [comment]
Bro you gotta put the release dates in the READMEs for all these V projects

**Comment by kiedtl** [comment]
> July 7.

It's already July 7th :astonished: Where's vid???

**Comment by anthony-y** [comment]
> It's already July 7th 😲 Where's vid???

It's the 5th lol

**Comment by kiedtl** [comment]
> It's the 5th lol

xD my calendar (and my eyes) completely glitched out lol

**Comment by bin** [comment]
So, it's the seventh.  Any updates?

**Comment by medvednikov** [comment]
Sorry, I have a presentation in a different city. Everything is ready for the release, but I don't want to do it while I'm away. I've postponed it by 2 days.

**Comment by bin** [comment]
Will this be released cross-platform, or with only certain ones?

**Comment by medvednikov** [comment]
All 3 operating systems. 

I forgot that I would be moving house today. That’s why I never wanted to do hard deadlines anymore :) it will be ready when it’s ready.

**Comment by noscript** [comment]
>Everything is ready for the release

Isn't it ready?

**Comment by notAlaanor** [comment]
bruh how you forget u moving house like that's a pretty significant event :/

**Comment by Borderliner** [comment]
Jeez people, don't put Alex under pressure for no reason. He obviously has a lot to do, and a whole language to maintain. Being patient is the least we can do to appreciate his efforts.

**Comment by dengsgo** [comment]
So, what happened, I haven't seen the release yet.
