### ISSUE TITLE
Slow on raspberry pi

### ISSUE THREAD

**Issue by kiedtl** [vlang/vid#38]
I'm not sure what's causing it, but lack of memory is surely not a problem. I'm on a Pi Zero W, running Arch Linux ARM with 512MB of memory (64MB for GPU), 1.000GHz cpu.

Vid takes about 10 seconds to show up, and takes almost 7 seconds for any action to take place.

Let me know if more information is needed.

**Comment by medvednikov** [comment]
Is the GPU driver installed?

**Comment by kiedtl** [comment]
> Is the GPU driver installed?

No, I wasn't aware that a driver was needed.

**Comment by medvednikov** [comment]
Right now only the opengl backend is available.

Xlib will be supported too in the future.

**Comment by medvednikov** [comment]
This is the limitation of the V graphics library.
